# Generated by Django 5.2 on 2025-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appliance_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='shipping_label',
            field=models.ImageField(blank=True, null=True, upload_to='shipping_labels/'),
        ),
    ]
